#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
"""
sim_linux.py
============

Boot a full BuildRoot Linux on a VexRiscv-SMP RISC-V SoC under Verilator.

The SoC is generated by LiteX and instantiates:
  - VexRiscv-SMP (32-bit, MMU, A-extension, Linux-capable)
  - Integrated ROM containing the LiteX BIOS
  - LiteDRAM SDRAM controller (model-backed in simulation)
  - Sim-UART exposed to the host as a serial console (serial2console)

The BIOS chain-loads OpenSBI from RAM (boot_ram0.json) which then jumps to
the Linux kernel (Image), which mounts the rootfs (rootfs.cpio) and gives
a login prompt as `buildroot login:`.

Run from the repository root:

    make sim-linux
    # or, manually:
    source .venv/bin/activate
    python3 sim/sim_linux.py
"""

import os
import sys
import json
import argparse

from migen import *

from litex.gen import LiteXModule
from litex.build.generic_platform import Pins, Subsignal
from litex.build.sim import SimPlatform
from litex.build.sim.config import SimConfig
from litex.build.sim.verilator import verilator_build_args, verilator_build_argdict

from litex.soc.integration.soc_core import *
from litex.soc.integration.builder import *
from litex.soc.integration.soc import SoCRegion
from litex.soc.cores.cpu.vexriscv_smp import VexRiscvSMP
from litex.soc.cores.bitbang import I2CMaster
from litex.soc.cores.gpio import GPIOTristate
from litex.soc.integration.common import get_mem_data
from litex.tools.litex_json2dts_linux import generate_dts

from litedram import modules as litedram_modules
from litedram.modules import parse_spd_hexdump
from litedram.common import *
from litedram.phy.model import sdram_module_nphases, get_sdram_phy_settings
from litedram.phy.model import SDRAMPHYModel


# Platform ---------------------------------------------------------------------

_io = [
    ("sys_clk", 0, Pins(1)),
    ("sys_rst", 0, Pins(1)),
    ("serial", 0,
        Subsignal("source_valid", Pins(1)),
        Subsignal("source_ready", Pins(1)),
        Subsignal("source_data",  Pins(8)),
        Subsignal("sink_valid",   Pins(1)),
        Subsignal("sink_ready",   Pins(1)),
        Subsignal("sink_data",    Pins(8)),
    ),
]


class Platform(SimPlatform):
    def __init__(self):
        SimPlatform.__init__(self, "SIM", _io)


# Supervisor (CSR-controlled $finish) ------------------------------------------

class Supervisor(LiteXModule):
    def __init__(self):
        from litex.soc.interconnect.csr import CSR
        self._finish = CSR()
        self.finish  = Signal()
        self.sync   += If(self._finish.re | self.finish, Finish())


# SoCLinux ---------------------------------------------------------------------

class PhotonicSoCLinux(SoCCore):
    def __init__(self,
                 sys_clk_freq      = int(100e6),
                 init_memories     = False,
                 sdram_module_name = "MT48LC16M16",
                 sdram_data_width  = 32,
                 sdram_verbosity   = 0,
                 images_dir        = "images"):

        platform = Platform()
        # We disable VCD trace dumping at runtime so Linux boots in reasonable
        # wall-clock time. The WDM fabric below has its own Icarus testbench
        # for waveform inspection.
        self.comb += platform.trace.eq(0)

        ram_init = []
        if init_memories:
            boot_image = os.path.join(images_dir, "boot_ram0.json")
            ram_init = get_mem_data(boot_image,
                                    endianness="little",
                                    offset=0x40000000)

        self.crg = CRG(platform.request("sys_clk"))

        SoCCore.__init__(self, platform,
            clk_freq            = sys_clk_freq,
            cpu_type            = "vexriscv_smp",
            cpu_variant         = "linux",
            integrated_rom_size = 0x10000,
            uart_name           = "sim",
        )
        self.add_config("DISABLE_DELAYS")
        self.add_constant("ROM_BOOT_ADDRESS", self.bus.regions["opensbi"].origin)

        self.supervisor = Supervisor()

        # SDRAM (model) --------------------------------------------------------
        sdram_clk_freq   = int(100e6)
        sdram_module_cls = getattr(litedram_modules, sdram_module_name)
        sdram_rate       = "1:{}".format(
            sdram_module_nphases[sdram_module_cls.memtype])
        sdram_module = sdram_module_cls(sdram_clk_freq, sdram_rate)
        phy_settings = get_sdram_phy_settings(
            memtype    = sdram_module.memtype,
            data_width = sdram_data_width,
            clk_freq   = sdram_clk_freq,
        )
        self.sdrphy = SDRAMPHYModel(
            module    = sdram_module,
            settings  = phy_settings,
            clk_freq  = sdram_clk_freq,
            verbosity = sdram_verbosity,
            init      = ram_init,
        )
        self.add_sdram("sdram",
            phy           = self.sdrphy,
            module        = sdram_module,
            l2_cache_size = 0,
        )
        self.add_constant("SDRAM_TEST_DISABLE")

    def generate_dts(self, build_dir):
        json_src = os.path.join(build_dir, "csr.json")
        dts      = os.path.join(build_dir, "sim.dts")
        with open(json_src) as f, open(dts, "w") as out:
            out.write(generate_dts(json.load(f)))

    def compile_dts(self, build_dir, images_dir):
        dts = os.path.join(build_dir, "sim.dts")
        dtb = os.path.join(images_dir, "rv32.dtb")
        os.system("dtc -O dtb -o {} {}".format(dtb, dts))


# Main -------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Boot Linux on a VexRiscv-SMP SoC under Verilator.")
    parser.add_argument("--sdram-module",     default="MT48LC16M16")
    parser.add_argument("--sdram-data-width", default=32, type=int)
    parser.add_argument("--sdram-verbosity",  default=0,  type=int)
    parser.add_argument("--build-dir",        default="build/sim")
    parser.add_argument("--images-dir",       default="images")
    VexRiscvSMP.args_fill(parser)
    verilator_build_args(parser)
    args = parser.parse_args()

    VexRiscvSMP.args_read(args)
    verilator_build_kwargs = verilator_build_argdict(args)

    sim_config = SimConfig(default_clk="sys_clk")
    sim_config.add_module("serial2console", "serial")

    # Two-pass build:
    #  pass 0: build everything except RAM init + generate DTS
    #  pass 1: build with RAM init from boot_ram0.json and run the simulator
    for i in range(2):
        prepare = (i == 0)
        run     = (i == 1)
        soc = PhotonicSoCLinux(
            init_memories     = run,
            sdram_module_name = args.sdram_module,
            sdram_data_width  = int(args.sdram_data_width),
            sdram_verbosity   = int(args.sdram_verbosity),
            images_dir        = args.images_dir,
        )
        builder = Builder(soc,
            output_dir       = args.build_dir,
            compile_gateware = run,
            csr_json         = os.path.join(args.build_dir, "csr.json"),
        )
        builder.build(sim_config=sim_config, run=run, **verilator_build_kwargs)
        if prepare:
            soc.generate_dts(args.build_dir)
            soc.compile_dts(args.build_dir, args.images_dir)


if __name__ == "__main__":
    sys.exit(main())
